name: Output workflow
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run input and output tests
        run: bash run_test.sh Tabkezelo/Tabkezelo generated_output.txt
      - name: Check results of input-output tests
        run: diff generated_output.txt expected_output.txt