name: Output workflow
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Run input and output tests
        run: bash Tabkezelo/run_test.sh main generated_output.txt
      - name: Check results of input-output tests
        run: diff Tabkezelo/generated_output.txt Tabkezelo/expected_output.txt