name: Mem test

on:
  push

jobs:
  build:
    name: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - run: sudo apt install valgrind
      - name: g++
        run: g++ -g Tabkezelo/Tabkezelo.cpp -o Tabkezelo
      - name: chmod Tabkezelo
        run: chmod +x Tabkezelo
      - name: leak test
        run: valgrind --leak-check=full --show-leak-kinds=all --error-exitcode=1 --track-origins=yes -s ./Tabkezelo < input.txt
